services:
  api-service:
    build: ./services/api-service
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    ports:
      - "8200:8000"
  
  traefik:
    image: traefik:v2.9
    command:
      - "--api.insecure=true"
      - "--providers.file.filename=/etc/traefik/routes.yml"
      - "--providers.file.watch=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "8180:80"
      - "8280:8080"
    volumes:
      - ./gateway/dynamic/routes.yml:/etc/traefik/routes.yml:ro
  
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"