services:
  api-service:
    build: ./services/api-service
    depends_on:
      - redis
      - inventory
      - kafka
      - consul
    environment:
      - REDIS_HOST=redis
      - CONSUL_HOST=consul
    ports:
      - "8200:8000"
      
  
  traefik:
    image: traefik:v2.9
    command:
      - "--api.insecure=true"
      - "--providers.file.filename=/etc/traefik/routes.yml"
      - "--providers.file.watch=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "8180:80"
      - "8280:8080"
    volumes:
      - ./gateway/dynamic/routes.yml:/etc/traefik/routes.yml:ro
  
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
  
  inventory:
    build: ./services/inventory-service
    container_name: inventory-service
    ports:
      - "50051:50051"
    environment:
      - CONSUL_HOST=consul

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  
  consul:
    image: hashicorp/consul:1.17
    container_name: consul
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    volumes:
      - ./discovery/consul/server.json:/consul/config/server.json
    command: "agent -dev -config-dir=/consul/config"